site_name: Zenseact MBT Framework
copyright: |-
  Copyright &copy; 2022-2023 Volvo Car Corporation //
  Copyright &copy; 2024-2025 Zenseact AB
repo_url: https://github.com/zenseact/zmbt-framework
# docs_dir: '.'

strict: true
hooks:
  - docs/hooks/preprocessor.py
nav:
  - Home: index.md
  # - Overview:
  # - Installation:
  # - Quick Start:
  - User Guide:
      - Signal Mapping Model: user-guide/signal-mapping.md
      - user-guide/expressions.md
      - user-guide/environment.md
      - user-guide/reflection.md
      - user-guide/concepts.md
  - DSL Reference:
      # - dsl-reference/overview.md
      - dsl-reference/signal-mapping.md
      - dsl-reference/expressions.md

  - C++ API:
    # - "CxxRef/links.md"
    - "Namespaces":
        - "Namespace List": "CxxRef/namespaces.md"
        - "Namespace Members": "CxxRef/namespace_members.md"
        - "Namespace Member Functions": "CxxRef/namespace_member_functions.md"
        - "Namespace Member Variables": "CxxRef/namespace_member_variables.md"
        - "Namespace Member Typedefs": "CxxRef/namespace_member_typedefs.md"
        - "Namespace Member Enumerations": "CxxRef/namespace_member_enums.md"
    - "Classes":
        - "Class List": "CxxRef/annotated.md"
        - "Class Index": "CxxRef/classes.md"
        - "Class Hierarchy": "CxxRef/hierarchy.md"
        - "Class Members": "CxxRef/class_members.md"
        - "Class Member Functions": "CxxRef/class_member_functions.md"
        - "Class Member Variables": "CxxRef/class_member_variables.md"
        - "Class Member Typedefs": "CxxRef/class_member_typedefs.md"
        - "Class Member Enumerations": "CxxRef/class_member_enums.md"
    - "Macros": "CxxRef/macros.md"
    - "Files": "CxxRef/files.md"

theme:
  name: material
  language: en
  features:
    - content.code.select
    - content.code.copy
    - content.code.annotate
    - navigation.footer
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  version:
    provider: mike

plugins:
  - search
  - tags
  - plantuml: # mkdocs_puml
      puml_url: https://www.plantuml.com/plantuml/
      puml_keyword: plantuml
  - mike:
      # These fields are all optional; the defaults are as below...
      alias_type: symlink
      redirect_template: null
      deploy_prefix: ''
      canonical_version: latest
      version_selector: true
      css_dir: css
      javascript_dir: js

  - mkdoxy:
      projects:
        CxxRef: # name of project must be alphanumeric + numbers (without spaces)
          src-dirs: zmbt-framework/backends/cxx # path to source code (support multiple paths separated by space) => INPUT
          # full-doc: True # if you want to generate full documentation
          doxy-cfg-file: docs/doxygen/Doxyfile
          doxy-cfg: # standard doxygen configuration (key: value)
            FILE_PATTERNS: "*.hpp* *.dox *.md" # specify file patterns to filter out
            RECURSIVE: True # recursive search in source directories

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - docs/javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
