@require(data)
/**
 * \file
 * \copyright (c) Copyright 2024-2025 Zenseact AB
 * \license SPDX-License-Identifier: Apache-2.0
 *
 * \details Autogenerated file - do not change!
 *
 * app: @appname
 * template: @template
 *
 * How to update:
 * 1. Update the template
 * 2. Run `python -m codegen` in the project root
 * 3. Commit changes
 */


#include "zmbt/expr/api.hpp"

#if defined(__clang__) || defined(__GNUC__)
#define ZMBT_EXPR_API_INIT __attribute__((init_priority(101)))
#else
#define ZMBT_EXPR_API_INIT
#endif

namespace zmbt {
namespace expr {

@for keyword in data.ApiKeywords:
lang::@keyword.Class const ZMBT_EXPR_API_INIT @keyword.Name = {};
@for alias in keyword.Aliases:
lang::@keyword.Class const ZMBT_EXPR_API_INIT @alias.capitalize() = @keyword.Name;
@end
@end

} // namespace expr
} // namespace zmbt
