@require(data)
/**
 * \file
 * \copyright (c) Copyright 2024-2025 Zenseact AB
 * \license SPDX-License-Identifier: Apache-2.0
 *
 * \details Autogenerated file - do not change!
 *
 * app: @appname
 * template: @template
 *
 * How to update:
 * 1. Update the template
 * 2. Run `python -m codegen` in the project root
 * 3. Commit changes
 */

@for library in data.imports_for(data.Constants):
#include <@library>
@end

#include "zmbt/expr/operator.hpp"
#include "zmbt/expr/expression.hpp"


namespace zmbt {

boost::json::value zmbt::dsl::Expression::eval_Const(boost::json::value const&) const
{
    switch(keyword())
    {
@for keyword in data.Constants:
    case Keyword::@keyword.Enum: return @keyword.CodegenValue;
@end
    default:
        throw expression_error("got invalid const expression: %s", underlying());
        return nullptr;
    }
}

} // namespace zmbt

