@require(data)
/**
 * \file
 * \copyright (c) Copyright 2024-2025 Zenseact AB
 * \license SPDX-License-Identifier: Apache-2.0
 *
 * \details Autogenerated file - do not change!
 *
 * app: @appname
 * template: @template
 *
 * How to update:
 * 1. Update the template
 * 2. Run `python -m codegen` in the project root
 * 3. Commit changes
 */

#include "zmbt/expr/keyword.hpp"


namespace zmbt {
namespace dsl {
namespace detail {

bool isBinary(Keyword const& k)
{
    switch (k)
    {
@for keyword in data.BinarySignatures:
    case Keyword::@keyword.Enum:
@end
        return true;
    default:
        return false;
    }
}

} // namespace detail
} // namespace dsl
} // namespace zmbt
