@require(keyword_groups)
@(from expr_helpers import Keyword)

/**
 * \file
 * \copyright (c) Copyright 2024-2025 Zenseact AB
 * \license SPDX-License-Identifier: Apache-2.0
 *
 * \details Autogenerated file - do not change!
 *
 * How to update:
 * 1. Update the template at `templates/expr/expression_api.hpp`
 * 2. Update the keyword data at `templates/expr/keywords.yaml`
 * 3. Regenerate file with `bazel run //templates/expr:expression_api_hpp > zmbt-framework/backends/cxx/include/zmbt/model/expression_api.hpp`
 * 4. Commit changes
 */

#ifndef ZMBT_MODEL_EXPRESSION_API_HPP_
#define ZMBT_MODEL_EXPRESSION_API_HPP_

#include "expression_api_signatures.hpp"

namespace zmbt {
namespace expr {

@for signature, group in keyword_groups.items():
@for keyword in Keyword.map(signature, group):

/// \brief @keyword.DocBrief
    @if details := keyword.DocDetails:
/// \details
        @for line in details.split('\n'):
/// @line
        @end
    @end
static signature::@keyword.Class const @keyword.Name;
@for alias in keyword.Aliases:
/// \brief Alias for @keyword.Name
static signature::@keyword.Class const @alias.capitalize();
@end
@end
@end

} // namespace expr
} // namespace zmbt

#endif // ZMBT_MAPPING_EXPRESSION_HPP_
