@require(keyword_groups)
@(from expr_helpers import Keyword)
/**
 * \file
 * \copyright (c) Copyright 2024-2025 Zenseact AB
 * \license SPDX-License-Identifier: Apache-2.0
 *
 * \details Autogenerated file - do not change!
 *
 * How to update:
 * 1. Update the template at `templates/expr/expression_api.hpp`
 * 2. Update the keyword data at `templates/expr/keywords.yaml`
 * 3. Regenerate file with `bazel run //templates/expr:expression_api_cpp > zmbt-framework/backends/cxx/src/model/expression_api.cpp`
 * 4. Commit changes
 */


#include "zmbt/model/expression_api.hpp"

namespace zmbt {

@for signature, group in keyword_groups.items():
@for keyword in Keyword.map(signature, group):
expr::signature::@keyword.Class @keyword.Enum = {};
@for alias in keyword.Aliases:
expr::signature::@keyword.Class @alias.capitalize() = @keyword.Enum;
@end
@end
@end

} // namespace zmbt
