@require(data)
/**
 * \file
 * \copyright (c) Copyright 2025 Zenseact AB
 * \license SPDX-License-Identifier: Apache-2.0
 *
 * \details Autogenerated file - do not change!
 *
 * app: @appname
 * template: @template
 *
 * How to update:
 * 1. Update the template
 * 2. Run `python -m codegen` in the project root
 * 3. Commit changes
 */
#include "zmbt/mapping/model_definition_states.hpp"
#include "zmbt/mapping/model_definition_transitions.hpp"


namespace zmbt {
namespace mapping {

@for t in data.Transitions:
template class ModelDefinition::@t.Class<ModelDefinition::@t.Source, ModelDefinition::@t.Target>;
@end

}  // namespace mapping
}  // namespace zmbt
