@require(data)
/**
 * \file
 * \copyright (c) Copyright 2024-2025 Zenseact AB
 * \license SPDX-License-Identifier: Apache-2.0
 *
 * \details Autogenerated file - do not change!
 *
 * app: @appname
 * template: @template
 *
 * How to update:
 * 1. Update the template
 * 2. Run `python -m codegen` in the project root
 * 3. Commit changes
 */


#ifndef ZMBT_MAPPING_MODEL_DEFINITION_HPP_
#define ZMBT_MAPPING_MODEL_DEFINITION_HPP_

#include "model_definition_helper.hpp"



namespace zmbt {
namespace mapping {

/// Mapping model definition machine
class ModelDefinition
{


    /// Base node class
    class BaseTransition;

    friend class SignalMapping;

    struct N_Term;

    // Transition templates
@for t in data.AbstractTransitions:
    /// @t transition
    template <class Target>
    struct @t;
@end

// NODES forward declarations
@for n in data.Nodes:
    /// @n.Class node
    class @n.Class;
@end

};


}  // namespace mapping
}  // namespace zmbt

#endif
