@require(data)
/**
 * \file
 * \copyright (c) Copyright 2024-2025 Zenseact AB
 * \license SPDX-License-Identifier: Apache-2.0
 *
 * \details Autogenerated file - do not change!
 *
 * app: @appname
 * template: @template
 *
 * How to update:
 * 1. Update the template
 * 2. Run `python -m codegen` in the project root
 * 3. Commit changes
 */

#ifndef ZMBT_MAPPING_MODEL_DEFINITION_STATES_HPP_
#define ZMBT_MAPPING_MODEL_DEFINITION_STATES_HPP_

#include "zmbt/mapping/model_definition.hpp"
#include "zmbt/mapping/model_definition_node.hpp"
#include "zmbt/mapping/model_definition_transitions.hpp"

namespace zmbt {
namespace mapping {

@for node in data.Nodes:
class ModelDefinition::@node.Class @node.BasesList
{
  private:
    friend class ModelDefinition;
    @{node.Class}(detail::DefinitionHelper&& m) : ModelDefinition::BaseTransition(std::move(m))
    {
    }
    @{node.Class}(@{node.Class} const&) = delete;
    @{node.Class}(@{node.Class}&&) = default;

  public:
    @{node.Class}() : @{node.Class}(detail::DefinitionHelper{}) {}
    virtual ~@{node.Class}()
    {
    }
};

@end

@for t in data.Transitions:
extern template class ModelDefinition::@t.Class<ModelDefinition::@t.Target>;
@end

}  // namespace mapping
}  // namespace zmbt

#endif
