/**
 * \file
 * \copyright (c) Copyright 2024-2025 Zenseact AB
 * \license SPDX-License-Identifier: Apache-2.0
 *
 * \details Autogenerated file - do not change!
 *
 * app: codegen.expr
 * template: codegen/expr/templates/zmbt-framework/backends/cxx/src/expr/api.cpp
 *
 * How to update:
 * 1. Update the template
 * 2. Run `python -m codegen` in the project root
 * 3. Commit changes
 */


#include "zmbt/expr/api.hpp"

#if defined(__clang__) || defined(__GNUC__)
#define ZMBT_EXPR_API_INIT __attribute__((init_priority(101)))
#else
#define ZMBT_EXPR_API_INIT
#endif

namespace zmbt {
namespace expr {

lang::SignatureConst<::zmbt::lang::Keyword::Noop> const ZMBT_EXPR_API_INIT Noop = {};
lang::SignatureConst<::zmbt::lang::Keyword::Noop> const ZMBT_EXPR_API_INIT _ = Noop;
lang::SignatureConst<::zmbt::lang::Keyword::Null> const ZMBT_EXPR_API_INIT Null = {};
lang::SignatureConst<::zmbt::lang::Keyword::True> const ZMBT_EXPR_API_INIT True = {};
lang::SignatureConst<::zmbt::lang::Keyword::False> const ZMBT_EXPR_API_INIT False = {};
lang::SignatureConst<::zmbt::lang::Keyword::Pi> const ZMBT_EXPR_API_INIT Pi = {};
lang::SignatureConst<::zmbt::lang::Keyword::E> const ZMBT_EXPR_API_INIT E = {};
lang::SignatureConst<::zmbt::lang::Keyword::Inf> const ZMBT_EXPR_API_INIT Inf = {};
lang::SignatureConst<::zmbt::lang::Keyword::Eps> const ZMBT_EXPR_API_INIT Eps = {};
lang::SignatureConst<::zmbt::lang::Keyword::NaN> const ZMBT_EXPR_API_INIT NaN = {};
lang::SignatureConst<::zmbt::lang::Keyword::Thread> const ZMBT_EXPR_API_INIT Thread = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Sin> const ZMBT_EXPR_API_INIT Sin = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Cos> const ZMBT_EXPR_API_INIT Cos = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Tan> const ZMBT_EXPR_API_INIT Tan = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Asin> const ZMBT_EXPR_API_INIT Asin = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Acos> const ZMBT_EXPR_API_INIT Acos = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Atan> const ZMBT_EXPR_API_INIT Atan = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Sinh> const ZMBT_EXPR_API_INIT Sinh = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Cosh> const ZMBT_EXPR_API_INIT Cosh = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Tanh> const ZMBT_EXPR_API_INIT Tanh = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Asinh> const ZMBT_EXPR_API_INIT Asinh = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Acosh> const ZMBT_EXPR_API_INIT Acosh = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Atanh> const ZMBT_EXPR_API_INIT Atanh = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Exp> const ZMBT_EXPR_API_INIT Exp = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Erf> const ZMBT_EXPR_API_INIT Erf = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Erfc> const ZMBT_EXPR_API_INIT Erfc = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Gamma> const ZMBT_EXPR_API_INIT Gamma = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Abs> const ZMBT_EXPR_API_INIT Abs = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Ceil> const ZMBT_EXPR_API_INIT Ceil = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Floor> const ZMBT_EXPR_API_INIT Floor = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Round> const ZMBT_EXPR_API_INIT Round = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Sqrt> const ZMBT_EXPR_API_INIT Sqrt = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Sign> const ZMBT_EXPR_API_INIT Sign = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Neg> const ZMBT_EXPR_API_INIT Neg = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Add> const ZMBT_EXPR_API_INIT Add = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Sub> const ZMBT_EXPR_API_INIT Sub = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Mul> const ZMBT_EXPR_API_INIT Mul = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Div> const ZMBT_EXPR_API_INIT Div = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Pow> const ZMBT_EXPR_API_INIT Pow = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Log> const ZMBT_EXPR_API_INIT Log = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Mod> const ZMBT_EXPR_API_INIT Mod = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Quot> const ZMBT_EXPR_API_INIT Quot = {};
lang::SignatureUnary<::zmbt::lang::Keyword::BitNot> const ZMBT_EXPR_API_INIT BitNot = {};
lang::SignatureBinary<::zmbt::lang::Keyword::BitAnd> const ZMBT_EXPR_API_INIT BitAnd = {};
lang::SignatureBinary<::zmbt::lang::Keyword::BitOr> const ZMBT_EXPR_API_INIT BitOr = {};
lang::SignatureBinary<::zmbt::lang::Keyword::BitXor> const ZMBT_EXPR_API_INIT BitXor = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Lshift> const ZMBT_EXPR_API_INIT Lshift = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Rshift> const ZMBT_EXPR_API_INIT Rshift = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Eq> const ZMBT_EXPR_API_INIT Eq = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Ne> const ZMBT_EXPR_API_INIT Ne = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Lt> const ZMBT_EXPR_API_INIT Lt = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Le> const ZMBT_EXPR_API_INIT Le = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Gt> const ZMBT_EXPR_API_INIT Gt = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Ge> const ZMBT_EXPR_API_INIT Ge = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Near> const ZMBT_EXPR_API_INIT Near = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Near> const ZMBT_EXPR_API_INIT Approx = Near;
lang::SignatureBinary<::zmbt::lang::Keyword::Union> const ZMBT_EXPR_API_INIT Union = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Intersect> const ZMBT_EXPR_API_INIT Intersect = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Diff> const ZMBT_EXPR_API_INIT Diff = {};
lang::SignatureBinary<::zmbt::lang::Keyword::SetEq> const ZMBT_EXPR_API_INIT SetEq = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Subset> const ZMBT_EXPR_API_INIT Subset = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Superset> const ZMBT_EXPR_API_INIT Superset = {};
lang::SignatureBinary<::zmbt::lang::Keyword::PSubset> const ZMBT_EXPR_API_INIT PSubset = {};
lang::SignatureBinary<::zmbt::lang::Keyword::PSuperset> const ZMBT_EXPR_API_INIT PSuperset = {};
lang::SignatureBinary<::zmbt::lang::Keyword::In> const ZMBT_EXPR_API_INIT In = {};
lang::SignatureBinary<::zmbt::lang::Keyword::NotIn> const ZMBT_EXPR_API_INIT NotIn = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Ni> const ZMBT_EXPR_API_INIT Ni = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Ni> const ZMBT_EXPR_API_INIT Contains = Ni;
lang::SignatureBinary<::zmbt::lang::Keyword::NotNi> const ZMBT_EXPR_API_INIT NotNi = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Bool> const ZMBT_EXPR_API_INIT Bool = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Bool> const ZMBT_EXPR_API_INIT Truthy = Bool;
lang::SignatureUnary<::zmbt::lang::Keyword::Not> const ZMBT_EXPR_API_INIT Not = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Not> const ZMBT_EXPR_API_INIT Falsy = Not;
lang::SignatureUnary<::zmbt::lang::Keyword::Not> const ZMBT_EXPR_API_INIT Nil = Not;
lang::SignatureBinary<::zmbt::lang::Keyword::And> const ZMBT_EXPR_API_INIT And = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Or> const ZMBT_EXPR_API_INIT Or = {};
lang::SignatureVariadic<::zmbt::lang::Keyword::If> const ZMBT_EXPR_API_INIT If = {};
lang::SignatureVariadic<::zmbt::lang::Keyword::Elif> const ZMBT_EXPR_API_INIT Elif = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Else> const ZMBT_EXPR_API_INIT Else = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Id> const ZMBT_EXPR_API_INIT Id = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Transp> const ZMBT_EXPR_API_INIT Transp = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Cartesian> const ZMBT_EXPR_API_INIT Cartesian = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Reverse> const ZMBT_EXPR_API_INIT Reverse = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Uniques> const ZMBT_EXPR_API_INIT Uniques = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Items> const ZMBT_EXPR_API_INIT Items = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Keys> const ZMBT_EXPR_API_INIT Keys = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Values> const ZMBT_EXPR_API_INIT Values = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Enumerate> const ZMBT_EXPR_API_INIT Enumerate = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Flatten> const ZMBT_EXPR_API_INIT Flatten = {};
lang::SignatureUnary<::zmbt::lang::Keyword::ToList> const ZMBT_EXPR_API_INIT ToList = {};
lang::SignatureUnary<::zmbt::lang::Keyword::First> const ZMBT_EXPR_API_INIT First = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Last> const ZMBT_EXPR_API_INIT Last = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Rand> const ZMBT_EXPR_API_INIT Rand = {};
lang::SignatureVariadic<::zmbt::lang::Keyword::RandInt> const ZMBT_EXPR_API_INIT RandInt = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Sequence> const ZMBT_EXPR_API_INIT Sequence = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Sequence> const ZMBT_EXPR_API_INIT Seq = Sequence;
lang::SignatureUnary<::zmbt::lang::Keyword::Arange> const ZMBT_EXPR_API_INIT Arange = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Parse> const ZMBT_EXPR_API_INIT Parse = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Str> const ZMBT_EXPR_API_INIT Str = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Str> const ZMBT_EXPR_API_INIT Serialize = Str;
lang::SignatureBinary<::zmbt::lang::Keyword::Re> const ZMBT_EXPR_API_INIT Re = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Re> const ZMBT_EXPR_API_INIT Regex = Re;
lang::SignatureVariadic<::zmbt::lang::Keyword::Fmt> const ZMBT_EXPR_API_INIT Fmt = {};
lang::SignatureVariadic<::zmbt::lang::Keyword::Fmt> const ZMBT_EXPR_API_INIT Format = Fmt;
lang::SignatureUnary<::zmbt::lang::Keyword::Capitalize> const ZMBT_EXPR_API_INIT Capitalize = {};
lang::SignatureUnary<::zmbt::lang::Keyword::LowerCase> const ZMBT_EXPR_API_INIT LowerCase = {};
lang::SignatureUnary<::zmbt::lang::Keyword::UpperCase> const ZMBT_EXPR_API_INIT UpperCase = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Card> const ZMBT_EXPR_API_INIT Card = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Size> const ZMBT_EXPR_API_INIT Size = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Sum> const ZMBT_EXPR_API_INIT Sum = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Prod> const ZMBT_EXPR_API_INIT Prod = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Avg> const ZMBT_EXPR_API_INIT Avg = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Slide> const ZMBT_EXPR_API_INIT Slide = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Stride> const ZMBT_EXPR_API_INIT Stride = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Chunks> const ZMBT_EXPR_API_INIT Chunks = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Repeat> const ZMBT_EXPR_API_INIT Repeat = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Cat> const ZMBT_EXPR_API_INIT Cat = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Cat> const ZMBT_EXPR_API_INIT Concat = Cat;
lang::SignatureBinary<::zmbt::lang::Keyword::Push> const ZMBT_EXPR_API_INIT Push = {};
lang::SignatureBinary<::zmbt::lang::Keyword::At> const ZMBT_EXPR_API_INIT At = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Del> const ZMBT_EXPR_API_INIT Del = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Del> const ZMBT_EXPR_API_INIT Delete = Del;
lang::SignatureBinary<::zmbt::lang::Keyword::Lookup> const ZMBT_EXPR_API_INIT Lookup = {};
lang::SignatureCast const ZMBT_EXPR_API_INIT Cast = {};
lang::SignatureCast const ZMBT_EXPR_API_INIT Decorate = Cast;
lang::SignatureUncast const ZMBT_EXPR_API_INIT Uncast = {};
lang::SignatureUncast const ZMBT_EXPR_API_INIT Undecorate = Uncast;
lang::SignatureBinary<::zmbt::lang::Keyword::Fold> const ZMBT_EXPR_API_INIT Fold = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Fold> const ZMBT_EXPR_API_INIT Reduce = Fold;
lang::SignatureBinary<::zmbt::lang::Keyword::Map> const ZMBT_EXPR_API_INIT Map = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Filter> const ZMBT_EXPR_API_INIT Filter = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Count> const ZMBT_EXPR_API_INIT Count = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Each> const ZMBT_EXPR_API_INIT Each = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Sort> const ZMBT_EXPR_API_INIT Sort = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Find> const ZMBT_EXPR_API_INIT Find = {};
lang::SignatureBinary<::zmbt::lang::Keyword::FindPtr> const ZMBT_EXPR_API_INIT FindPtr = {};
lang::SignatureBinary<::zmbt::lang::Keyword::FindIdx> const ZMBT_EXPR_API_INIT FindIdx = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Min> const ZMBT_EXPR_API_INIT Min = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Max> const ZMBT_EXPR_API_INIT Max = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Argmin> const ZMBT_EXPR_API_INIT Argmin = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Argmax> const ZMBT_EXPR_API_INIT Argmax = {};
lang::SignatureVariadic<::zmbt::lang::Keyword::Recur> const ZMBT_EXPR_API_INIT Recur = {};
lang::SignatureVariadic<::zmbt::lang::Keyword::Unfold> const ZMBT_EXPR_API_INIT Unfold = {};
lang::SignatureOp const ZMBT_EXPR_API_INIT Op = {};
lang::SignatureOp const ZMBT_EXPR_API_INIT Overload = Op;
lang::SignatureBinary<::zmbt::lang::Keyword::Bind> const ZMBT_EXPR_API_INIT Bind = {};
lang::SignatureVariadic<::zmbt::lang::Keyword::Fn> const ZMBT_EXPR_API_INIT Fn = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Link> const ZMBT_EXPR_API_INIT Link = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Get> const ZMBT_EXPR_API_INIT Get = {};
lang::SignatureBinary<::zmbt::lang::Keyword::EnvLoad> const ZMBT_EXPR_API_INIT EnvLoad = {};
lang::SignatureBinary<::zmbt::lang::Keyword::EnvStore> const ZMBT_EXPR_API_INIT EnvStore = {};
lang::SignatureVariadic<::zmbt::lang::Keyword::Any> const ZMBT_EXPR_API_INIT Any = {};
lang::SignatureVariadic<::zmbt::lang::Keyword::All> const ZMBT_EXPR_API_INIT All = {};
lang::SignatureVariadic<::zmbt::lang::Keyword::Saturate> const ZMBT_EXPR_API_INIT Saturate = {};
lang::SignatureVariadic<::zmbt::lang::Keyword::Pipe> const ZMBT_EXPR_API_INIT Pipe = {};
lang::SignatureVariadic<::zmbt::lang::Keyword::Tuple> const ZMBT_EXPR_API_INIT Tuple = {};
lang::SignatureVariadic<::zmbt::lang::Keyword::Fork> const ZMBT_EXPR_API_INIT Fork = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Flip> const ZMBT_EXPR_API_INIT Flip = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Dbg> const ZMBT_EXPR_API_INIT Dbg = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Dbg> const ZMBT_EXPR_API_INIT Debug = Dbg;
lang::SignatureBinary<::zmbt::lang::Keyword::Eval> const ZMBT_EXPR_API_INIT Eval = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Try> const ZMBT_EXPR_API_INIT Try = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Kwrd> const ZMBT_EXPR_API_INIT Kwrd = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Prms> const ZMBT_EXPR_API_INIT Prms = {};
lang::SignatureUnary<::zmbt::lang::Keyword::Prms> const ZMBT_EXPR_API_INIT Parameters = Prms;
lang::SignatureBinary<::zmbt::lang::Keyword::Q> const ZMBT_EXPR_API_INIT Q = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Q> const ZMBT_EXPR_API_INIT C = Q;
lang::SignatureBinary<::zmbt::lang::Keyword::Q> const ZMBT_EXPR_API_INIT Const = Q;
lang::SignatureBinary<::zmbt::lang::Keyword::D> const ZMBT_EXPR_API_INIT D = {};
lang::SignatureBinary<::zmbt::lang::Keyword::D> const ZMBT_EXPR_API_INIT Default = D;
lang::SignatureErr const ZMBT_EXPR_API_INIT Err = {};
lang::SignatureErr const ZMBT_EXPR_API_INIT Error = Err;
lang::SignatureUnary<::zmbt::lang::Keyword::IsErr> const ZMBT_EXPR_API_INIT IsErr = {};
lang::SignatureUnary<::zmbt::lang::Keyword::IsErr> const ZMBT_EXPR_API_INIT Iserror = IsErr;
lang::SignatureBinary<::zmbt::lang::Keyword::Assert> const ZMBT_EXPR_API_INIT Assert = {};
lang::SignatureBinary<::zmbt::lang::Keyword::Trace> const ZMBT_EXPR_API_INIT Trace = {};
lang::SignatureBinary<::zmbt::lang::Keyword::PreProc> const ZMBT_EXPR_API_INIT PreProc = {};

} // namespace expr
} // namespace zmbt
