/**
 * \file
 * \copyright (c) Copyright 2024-2025 Zenseact AB
 * \license SPDX-License-Identifier: Apache-2.0
 *
 * \details Autogenerated file - do not change!
 *
 * app: codegen.expr
 * template: codegen/mdm/templates/model_definition.hpp
 *
 * How to update:
 * 1. Update the template
 * 2. Run `python -m codegen` in the project root
 * 3. Commit changes
 */


#ifndef ZMBT_MAPPING_MODEL_DEFINITION_HPP_
#define ZMBT_MAPPING_MODEL_DEFINITION_HPP_

#include "model_definition_helper.hpp"



namespace zmbt {
namespace mapping {

/// Mapping model definition machine
class ModelDefinition
{
    detail::DefinitionHelper mapping_;

  public:
    ModelDefinition() : mapping_{} {}
    ModelDefinition(detail::DefinitionHelper& mapping) : mapping_{mapping} {}

    detail::DefinitionHelper& state()
    {
        return mapping_;
    }
  protected:


    /// \brief  Empty transition
    /// \tparam Source
    /// \tparam Target
    template <class Source, class Target>
    struct T_Null {};

    // Transition templates
    /// T_Alias transition
    template <class Source, class Target>
    struct T_Alias;
    /// T_Args transition
    template <class Source, class Target>
    struct T_Args;
    /// T_As transition
    template <class Source, class Target>
    struct T_As;
    /// T_CallCount transition
    template <class Source, class Target>
    struct T_CallCount;
    /// T_CallRange transition
    template <class Source, class Target>
    struct T_CallRange;
    /// T_CallRangeIn transition
    template <class Source, class Target>
    struct T_CallRangeIn;
    /// T_Description transition
    template <class Source, class Target>
    struct T_Description;
    /// T_Exception transition
    template <class Source, class Target>
    struct T_Exception;
    /// T_InjectTo transition
    template <class Source, class Target>
    struct T_InjectTo;
    /// T_ObserveOn transition
    template <class Source, class Target>
    struct T_ObserveOn;
    /// T_OnCall transition
    template <class Source, class Target>
    struct T_OnCall;
    /// T_OnTrigger transition
    template <class Source, class Target>
    struct T_OnTrigger;
    /// T_ParamRow transition
    template <class Source, class Target>
    struct T_ParamRow;
    /// T_PostRun transition
    template <class Source, class Target>
    struct T_PostRun;
    /// T_PreRun transition
    template <class Source, class Target>
    struct T_PreRun;
    /// T_Prod transition
    template <class Source, class Target>
    struct T_Prod;
    /// T_Repeat transition
    template <class Source, class Target>
    struct T_Repeat;
    /// T_Return transition
    template <class Source, class Target>
    struct T_Return;
    /// T_Test transition
    template <class Source, class Target>
    struct T_Test;
    /// T_TestComment transition
    template <class Source, class Target>
    struct T_TestComment;
    /// T_TestRow transition
    template <class Source, class Target>
    struct T_TestRow;
    /// T_ThreadId transition
    template <class Source, class Target>
    struct T_ThreadId;
    /// T_Timestamp transition
    template <class Source, class Target>
    struct T_Timestamp;
    /// T_Union transition
    template <class Source, class Target>
    struct T_Union;
    /// T_With transition
    template <class Source, class Target>
    struct T_With;
    /// T_Zip transition
    template <class Source, class Target>
    struct T_Zip;

// NODES forward declarations
    /// N_Term node
    class N_Term;
    /// N_Descr node
    class N_Descr;
    /// N_Post node
    class N_Post;
    /// N_Pre node
    class N_Pre;
    /// N_ParamTable node
    class N_ParamTable;
    /// N_Param node
    class N_Param;
    /// N_TestTable node
    class N_TestTable;
    /// N_Test node
    class N_Test;
    /// N_Channel node
    class N_Channel;
    /// N_ChannelOut node
    class N_ChannelOut;
    /// N_Combine node
    class N_Combine;
    /// N_Alias node
    class N_Alias;
    /// N_AliasOut node
    class N_AliasOut;
    /// N_Call node
    class N_Call;
    /// N_CallOut node
    class N_CallOut;
    /// N_Decor node
    class N_Decor;
    /// N_DecorOut node
    class N_DecorOut;
    /// N_KindIn node
    class N_KindIn;
    /// N_KindOut node
    class N_KindOut;
    /// N_Repeat node
    class N_Repeat;
    /// N_Main node
    class N_Main;

    /// Base node class
    class N_Node;

    friend class SignalMapping;

};


}  // namespace mapping
}  // namespace zmbt

#endif
