/**
 * \file
 * \copyright (c) Copyright 2024-2025 Zenseact AB
 * \license SPDX-License-Identifier: Apache-2.0
 *
 * \details Autogenerated file - do not change!
 *
 * app: codegen.expr
 * template: codegen/expr/templates/keyword_grammar.cpp
 *
 * How to update:
 * 1. Update the template
 * 2. Run `python -m codegen` in the project root
 * 3. Commit changes
 */

#include <boost/spirit/include/qi.hpp>

#include "zmbt/model/keyword.hpp"
#include "zmbt/model/keyword_grammar.hpp"

#ifndef ZMBT_KEYWORD_PREFIX
    #define ZMBT_KEYWORD_PREFIX ":"
#endif

namespace qi = boost::spirit::qi;

namespace zmbt
{

KeywordSymbol::KeywordSymbol()
{
    add
    (ZMBT_KEYWORD_PREFIX "literal", zmbt::Keyword::Literal)
    (ZMBT_KEYWORD_PREFIX "void", zmbt::Keyword::Void)
    (ZMBT_KEYWORD_PREFIX "noop", zmbt::Keyword::Noop)
    (ZMBT_KEYWORD_PREFIX "n/a", zmbt::Keyword::Noop)
    (ZMBT_KEYWORD_PREFIX "_", zmbt::Keyword::Noop)
    (ZMBT_KEYWORD_PREFIX "null", zmbt::Keyword::Null)
    (ZMBT_KEYWORD_PREFIX "true", zmbt::Keyword::True)
    (ZMBT_KEYWORD_PREFIX "T", zmbt::Keyword::True)
    (ZMBT_KEYWORD_PREFIX "false", zmbt::Keyword::False)
    (ZMBT_KEYWORD_PREFIX "⊥", zmbt::Keyword::False)
    (ZMBT_KEYWORD_PREFIX "pi", zmbt::Keyword::Pi)
    (ZMBT_KEYWORD_PREFIX "π", zmbt::Keyword::Pi)
    (ZMBT_KEYWORD_PREFIX "e", zmbt::Keyword::E)
    (ZMBT_KEYWORD_PREFIX "inf", zmbt::Keyword::Inf)
    (ZMBT_KEYWORD_PREFIX "eps", zmbt::Keyword::Eps)
    (ZMBT_KEYWORD_PREFIX "nan", zmbt::Keyword::NaN)
    (ZMBT_KEYWORD_PREFIX "bool", zmbt::Keyword::Bool)
    (ZMBT_KEYWORD_PREFIX "?", zmbt::Keyword::Bool)
    (ZMBT_KEYWORD_PREFIX "nil", zmbt::Keyword::Nil)
    (ZMBT_KEYWORD_PREFIX "not", zmbt::Keyword::Not)
    (ZMBT_KEYWORD_PREFIX "¬", zmbt::Keyword::Not)
    (ZMBT_KEYWORD_PREFIX "neg", zmbt::Keyword::Neg)
    (ZMBT_KEYWORD_PREFIX "b-not", zmbt::Keyword::BitNot)
    (ZMBT_KEYWORD_PREFIX "~", zmbt::Keyword::BitNot)
    (ZMBT_KEYWORD_PREFIX "sqrt", zmbt::Keyword::Sqrt)
    (ZMBT_KEYWORD_PREFIX "sin", zmbt::Keyword::Sin)
    (ZMBT_KEYWORD_PREFIX "cos", zmbt::Keyword::Cos)
    (ZMBT_KEYWORD_PREFIX "tan", zmbt::Keyword::Tan)
    (ZMBT_KEYWORD_PREFIX "asin", zmbt::Keyword::Asin)
    (ZMBT_KEYWORD_PREFIX "acos", zmbt::Keyword::Acos)
    (ZMBT_KEYWORD_PREFIX "atan", zmbt::Keyword::Atan)
    (ZMBT_KEYWORD_PREFIX "sinh", zmbt::Keyword::Sinh)
    (ZMBT_KEYWORD_PREFIX "cosh", zmbt::Keyword::Cosh)
    (ZMBT_KEYWORD_PREFIX "tanh", zmbt::Keyword::Tanh)
    (ZMBT_KEYWORD_PREFIX "asinh", zmbt::Keyword::Asinh)
    (ZMBT_KEYWORD_PREFIX "acosh", zmbt::Keyword::Acosh)
    (ZMBT_KEYWORD_PREFIX "atanh", zmbt::Keyword::Atanh)
    (ZMBT_KEYWORD_PREFIX "exp", zmbt::Keyword::Exp)
    (ZMBT_KEYWORD_PREFIX "erf", zmbt::Keyword::Erf)
    (ZMBT_KEYWORD_PREFIX "erfc", zmbt::Keyword::Erfc)
    (ZMBT_KEYWORD_PREFIX "gamma", zmbt::Keyword::Gamma)
    (ZMBT_KEYWORD_PREFIX "abs", zmbt::Keyword::Abs)
    (ZMBT_KEYWORD_PREFIX "ceil", zmbt::Keyword::Ceil)
    (ZMBT_KEYWORD_PREFIX "floor", zmbt::Keyword::Floor)
    (ZMBT_KEYWORD_PREFIX "sign", zmbt::Keyword::Sign)
    (ZMBT_KEYWORD_PREFIX "sum", zmbt::Keyword::Sum)
    (ZMBT_KEYWORD_PREFIX "Σ", zmbt::Keyword::Sum)
    (ZMBT_KEYWORD_PREFIX "prod", zmbt::Keyword::Prod)
    (ZMBT_KEYWORD_PREFIX "Π", zmbt::Keyword::Prod)
    (ZMBT_KEYWORD_PREFIX "round", zmbt::Keyword::Round)
    (ZMBT_KEYWORD_PREFIX "add", zmbt::Keyword::Add)
    (ZMBT_KEYWORD_PREFIX "+", zmbt::Keyword::Add)
    (ZMBT_KEYWORD_PREFIX "sub", zmbt::Keyword::Sub)
    (ZMBT_KEYWORD_PREFIX "-", zmbt::Keyword::Sub)
    (ZMBT_KEYWORD_PREFIX "sub-from", zmbt::Keyword::SubFrom)
    (ZMBT_KEYWORD_PREFIX "mul", zmbt::Keyword::Mul)
    (ZMBT_KEYWORD_PREFIX "*", zmbt::Keyword::Mul)
    (ZMBT_KEYWORD_PREFIX "div", zmbt::Keyword::Div)
    (ZMBT_KEYWORD_PREFIX "/", zmbt::Keyword::Div)
    (ZMBT_KEYWORD_PREFIX "div-from", zmbt::Keyword::DivFrom)
    (ZMBT_KEYWORD_PREFIX "pow", zmbt::Keyword::Pow)
    (ZMBT_KEYWORD_PREFIX "**", zmbt::Keyword::Pow)
    (ZMBT_KEYWORD_PREFIX "pow-from", zmbt::Keyword::PowFrom)
    (ZMBT_KEYWORD_PREFIX "log", zmbt::Keyword::Log)
    (ZMBT_KEYWORD_PREFIX "log", zmbt::Keyword::Log)
    (ZMBT_KEYWORD_PREFIX "log-from", zmbt::Keyword::LogFrom)
    (ZMBT_KEYWORD_PREFIX "mod", zmbt::Keyword::Mod)
    (ZMBT_KEYWORD_PREFIX "%", zmbt::Keyword::Mod)
    (ZMBT_KEYWORD_PREFIX "mod-from", zmbt::Keyword::ModFrom)
    (ZMBT_KEYWORD_PREFIX "quot", zmbt::Keyword::Quot)
    (ZMBT_KEYWORD_PREFIX "//", zmbt::Keyword::Quot)
    (ZMBT_KEYWORD_PREFIX "quot-from", zmbt::Keyword::QuotFrom)
    (ZMBT_KEYWORD_PREFIX "b-and", zmbt::Keyword::BitAnd)
    (ZMBT_KEYWORD_PREFIX "&", zmbt::Keyword::BitAnd)
    (ZMBT_KEYWORD_PREFIX "b-or", zmbt::Keyword::BitOr)
    (ZMBT_KEYWORD_PREFIX "|", zmbt::Keyword::BitOr)
    (ZMBT_KEYWORD_PREFIX "b-xor", zmbt::Keyword::BitXor)
    (ZMBT_KEYWORD_PREFIX "^", zmbt::Keyword::BitXor)
    (ZMBT_KEYWORD_PREFIX "b-lshift", zmbt::Keyword::BitLshift)
    (ZMBT_KEYWORD_PREFIX "<<", zmbt::Keyword::BitLshift)
    (ZMBT_KEYWORD_PREFIX "b-lshift-from", zmbt::Keyword::BitLshiftFrom)
    (ZMBT_KEYWORD_PREFIX "b-rshift", zmbt::Keyword::BitRshift)
    (ZMBT_KEYWORD_PREFIX ">>", zmbt::Keyword::BitRshift)
    (ZMBT_KEYWORD_PREFIX "b-rshift-from", zmbt::Keyword::BitRshiftFrom)
    (ZMBT_KEYWORD_PREFIX "eq", zmbt::Keyword::Eq)
    (ZMBT_KEYWORD_PREFIX "=", zmbt::Keyword::Eq)
    (ZMBT_KEYWORD_PREFIX "ne", zmbt::Keyword::Ne)
    (ZMBT_KEYWORD_PREFIX "≠", zmbt::Keyword::Ne)
    (ZMBT_KEYWORD_PREFIX "lt", zmbt::Keyword::Lt)
    (ZMBT_KEYWORD_PREFIX "<", zmbt::Keyword::Lt)
    (ZMBT_KEYWORD_PREFIX "le", zmbt::Keyword::Le)
    (ZMBT_KEYWORD_PREFIX "≤", zmbt::Keyword::Le)
    (ZMBT_KEYWORD_PREFIX "gt", zmbt::Keyword::Gt)
    (ZMBT_KEYWORD_PREFIX ">", zmbt::Keyword::Gt)
    (ZMBT_KEYWORD_PREFIX "ge", zmbt::Keyword::Ge)
    (ZMBT_KEYWORD_PREFIX "≥", zmbt::Keyword::Ge)
    (ZMBT_KEYWORD_PREFIX "approx", zmbt::Keyword::Approx)
    (ZMBT_KEYWORD_PREFIX "near", zmbt::Keyword::Approx)
    (ZMBT_KEYWORD_PREFIX "and", zmbt::Keyword::And)
    (ZMBT_KEYWORD_PREFIX "∧", zmbt::Keyword::And)
    (ZMBT_KEYWORD_PREFIX "or", zmbt::Keyword::Or)
    (ZMBT_KEYWORD_PREFIX "∨", zmbt::Keyword::Or)
    (ZMBT_KEYWORD_PREFIX "set-eq", zmbt::Keyword::SetEq)
    (ZMBT_KEYWORD_PREFIX "≡", zmbt::Keyword::SetEq)
    (ZMBT_KEYWORD_PREFIX "subset", zmbt::Keyword::Subset)
    (ZMBT_KEYWORD_PREFIX "⊆", zmbt::Keyword::Subset)
    (ZMBT_KEYWORD_PREFIX "superset", zmbt::Keyword::Superset)
    (ZMBT_KEYWORD_PREFIX "⊇", zmbt::Keyword::Superset)
    (ZMBT_KEYWORD_PREFIX "p-subset", zmbt::Keyword::ProperSubset)
    (ZMBT_KEYWORD_PREFIX "⊂", zmbt::Keyword::ProperSubset)
    (ZMBT_KEYWORD_PREFIX "p-superset", zmbt::Keyword::ProperSuperset)
    (ZMBT_KEYWORD_PREFIX "⊃", zmbt::Keyword::ProperSuperset)
    (ZMBT_KEYWORD_PREFIX "in", zmbt::Keyword::In)
    (ZMBT_KEYWORD_PREFIX "∈", zmbt::Keyword::In)
    (ZMBT_KEYWORD_PREFIX "not-in", zmbt::Keyword::NotIn)
    (ZMBT_KEYWORD_PREFIX "∉", zmbt::Keyword::NotIn)
    (ZMBT_KEYWORD_PREFIX "ni", zmbt::Keyword::Ni)
    (ZMBT_KEYWORD_PREFIX "∋", zmbt::Keyword::Ni)
    (ZMBT_KEYWORD_PREFIX "contains", zmbt::Keyword::Ni)
    (ZMBT_KEYWORD_PREFIX "not-ni", zmbt::Keyword::NotNi)
    (ZMBT_KEYWORD_PREFIX "∌", zmbt::Keyword::NotNi)
    (ZMBT_KEYWORD_PREFIX "union", zmbt::Keyword::Union)
    (ZMBT_KEYWORD_PREFIX "∪", zmbt::Keyword::Union)
    (ZMBT_KEYWORD_PREFIX "intersect", zmbt::Keyword::Intersect)
    (ZMBT_KEYWORD_PREFIX "∩", zmbt::Keyword::Intersect)
    (ZMBT_KEYWORD_PREFIX "set-diff", zmbt::Keyword::Diff)
    (ZMBT_KEYWORD_PREFIX "set-diff-from", zmbt::Keyword::DiffFrom)
    (ZMBT_KEYWORD_PREFIX "concat", zmbt::Keyword::Concat)
    (ZMBT_KEYWORD_PREFIX "cartesian", zmbt::Keyword::Cartesian)
    (ZMBT_KEYWORD_PREFIX "×", zmbt::Keyword::Cartesian)
    (ZMBT_KEYWORD_PREFIX "list", zmbt::Keyword::List)
    (ZMBT_KEYWORD_PREFIX "transp", zmbt::Keyword::Transp)
    (ZMBT_KEYWORD_PREFIX "uniques", zmbt::Keyword::Uniques)
    (ZMBT_KEYWORD_PREFIX "id", zmbt::Keyword::Id)
    (ZMBT_KEYWORD_PREFIX "card", zmbt::Keyword::Card)
    (ZMBT_KEYWORD_PREFIX "size", zmbt::Keyword::Size)
    (ZMBT_KEYWORD_PREFIX "slide", zmbt::Keyword::Slide)
    (ZMBT_KEYWORD_PREFIX "stride", zmbt::Keyword::Stride)
    (ZMBT_KEYWORD_PREFIX "repeat", zmbt::Keyword::Repeat)
    (ZMBT_KEYWORD_PREFIX "re", zmbt::Keyword::Re)
    (ZMBT_KEYWORD_PREFIX "regex", zmbt::Keyword::Re)
    (ZMBT_KEYWORD_PREFIX "at", zmbt::Keyword::At)
    (ZMBT_KEYWORD_PREFIX "map", zmbt::Keyword::Map)
    (ZMBT_KEYWORD_PREFIX "filter", zmbt::Keyword::Filter)
    (ZMBT_KEYWORD_PREFIX "count", zmbt::Keyword::Count)
    (ZMBT_KEYWORD_PREFIX "sort", zmbt::Keyword::Sort)
    (ZMBT_KEYWORD_PREFIX "min", zmbt::Keyword::Min)
    (ZMBT_KEYWORD_PREFIX "max", zmbt::Keyword::Max)
    (ZMBT_KEYWORD_PREFIX "argmin", zmbt::Keyword::Argmin)
    (ZMBT_KEYWORD_PREFIX "argmax", zmbt::Keyword::Argmax)
    (ZMBT_KEYWORD_PREFIX "recur", zmbt::Keyword::Recur)
    (ZMBT_KEYWORD_PREFIX "apply", zmbt::Keyword::Apply)
    (ZMBT_KEYWORD_PREFIX "bind", zmbt::Keyword::Bind)
    (ZMBT_KEYWORD_PREFIX "reduce", zmbt::Keyword::Reduce)
    (ZMBT_KEYWORD_PREFIX "any", zmbt::Keyword::Any)
    (ZMBT_KEYWORD_PREFIX "all", zmbt::Keyword::All)
    (ZMBT_KEYWORD_PREFIX "saturate", zmbt::Keyword::Saturate)
    (ZMBT_KEYWORD_PREFIX "compose", zmbt::Keyword::Compose)
    ;
}


KeywordGrammar::KeywordGrammar()
    : KeywordGrammar::base_type(start)
{
    using boost::spirit::qi::eps;
    using boost::spirit::qi::_val;
    using boost::spirit::qi::_1;

    start = eps [_val = Keyword::Undefined] >>
        (
            +keyword_symbol [_val = _1]
        )
    ;
}

} // namespace zmbt
