/**
 * \file
 * \copyright (c) Copyright 2024-2025 Zenseact AB
 * \license SPDX-License-Identifier: Apache-2.0
 *
 * \details Autogenerated file - do not change!
 *
 * app: codegen.expr
 * template: codegen/expr/templates/zmbt-framework/backends/cxx/src/model/keyword_codegen_type.cpp
 *
 * How to update:
 * 1. Update the template
 * 2. Run `python -m codegen` in the project root
 * 3. Commit changes
 */

#include "zmbt/model/keyword_codegen_type.hpp"


namespace zmbt {
namespace dsl {
namespace detail {


CodegenType getCodegenType(Keyword const& k)
{
    switch (k)
    {
    case Keyword::Noop:
    case Keyword::Null:
    case Keyword::True:
    case Keyword::False:
    case Keyword::Pi:
    case Keyword::E:
    case Keyword::Inf:
    case Keyword::Eps:
    case Keyword::NaN:
        return CodegenType::Const;
    case Keyword::Neg:
    case Keyword::BitNot:
    case Keyword::Bool:
    case Keyword::Nil:
    case Keyword::Not:
        return CodegenType::UnaryOp;
    case Keyword::Add:
    case Keyword::Sub:
    case Keyword::SubFrom:
    case Keyword::Mul:
    case Keyword::Div:
    case Keyword::DivFrom:
    case Keyword::Pow:
    case Keyword::PowFrom:
    case Keyword::Log:
    case Keyword::LogFrom:
    case Keyword::Mod:
    case Keyword::ModFrom:
    case Keyword::Quot:
    case Keyword::QuotFrom:
    case Keyword::BitAnd:
    case Keyword::BitOr:
    case Keyword::BitXor:
    case Keyword::BitLshift:
    case Keyword::BitLshiftFrom:
    case Keyword::BitRshift:
    case Keyword::BitRshiftFrom:
    case Keyword::Eq:
    case Keyword::Ne:
    case Keyword::Lt:
    case Keyword::Le:
    case Keyword::Gt:
    case Keyword::Ge:
    case Keyword::SetEq:
    case Keyword::Subset:
    case Keyword::Superset:
    case Keyword::ProperSubset:
    case Keyword::ProperSuperset:
    case Keyword::In:
    case Keyword::NotIn:
    case Keyword::Ni:
    case Keyword::NotNi:
    case Keyword::And:
    case Keyword::Or:
        return CodegenType::BinaryOp;
    case Keyword::Sin:
    case Keyword::Cos:
    case Keyword::Tan:
    case Keyword::Asin:
    case Keyword::Acos:
    case Keyword::Atan:
    case Keyword::Sinh:
    case Keyword::Cosh:
    case Keyword::Tanh:
    case Keyword::Asinh:
    case Keyword::Acosh:
    case Keyword::Atanh:
    case Keyword::Exp:
    case Keyword::Erf:
    case Keyword::Erfc:
    case Keyword::Gamma:
    case Keyword::Abs:
    case Keyword::Ceil:
    case Keyword::Floor:
    case Keyword::Round:
    case Keyword::Sqrt:
    case Keyword::Sign:
    case Keyword::Id:
    case Keyword::Parse:
    case Keyword::Serialize:
    case Keyword::Default:
        return CodegenType::CodegenFn;
    default:
        return CodegenType::None;
    }

}

} // namespace detail
} // namespace dsl
} // namespace zmbt
