/**
 * \file
 * \copyright (c) Copyright 2024 Zenseact AB
 * \license SPDX-License-Identifier: Apache-2.0
 *
 * \details Autogenerated file - do not change!
 *
 * How to update:
 * 1. Update the template at `templates/expr/keyword_grammar.cpp`
 * 2. Update the keyword data at `templates/expr/data.yaml`
 * 3. Regenerate file with `bazel run //templates/expr:keyword_grammar_cpp > zmbt-framework/backends/cxx/src/model/keyword_grammar.cpp`
 * 4. Commit changes
 */


#include <boost/spirit/include/qi.hpp>

#include "zmbt/model/keyword.hpp"
#include "zmbt/model/keyword_grammar.hpp"

#ifndef ZMBT_KEYWORD_PREFIX
    #define ZMBT_KEYWORD_PREFIX ":"
#endif

namespace qi = boost::spirit::qi;
namespace{
using Kw = zmbt::Keyword;
}

namespace zmbt
{

KeywordSymbol::KeywordSymbol()
{
    add
    (ZMBT_KEYWORD_PREFIX "id", Kw::Id)
    (ZMBT_KEYWORD_PREFIX "noop", Kw::Noop)
    (ZMBT_KEYWORD_PREFIX "n/a", Kw::Noop)
    (ZMBT_KEYWORD_PREFIX "true", Kw::True)
    (ZMBT_KEYWORD_PREFIX "T", Kw::True)
    (ZMBT_KEYWORD_PREFIX "false", Kw::False)
    (ZMBT_KEYWORD_PREFIX "⊥", Kw::False)
    (ZMBT_KEYWORD_PREFIX "null", Kw::Null)
    (ZMBT_KEYWORD_PREFIX "pi", Kw::Pi)
    (ZMBT_KEYWORD_PREFIX "π", Kw::Pi)
    (ZMBT_KEYWORD_PREFIX "e", Kw::E)
    (ZMBT_KEYWORD_PREFIX "inf", Kw::Inf)
    (ZMBT_KEYWORD_PREFIX "eps", Kw::Eps)
    (ZMBT_KEYWORD_PREFIX "nan", Kw::NaN)
    (ZMBT_KEYWORD_PREFIX "bool", Kw::Bool)
    (ZMBT_KEYWORD_PREFIX "?", Kw::Bool)
    (ZMBT_KEYWORD_PREFIX "nil", Kw::Nil)
    (ZMBT_KEYWORD_PREFIX "not", Kw::Not)
    (ZMBT_KEYWORD_PREFIX "¬", Kw::Not)
    (ZMBT_KEYWORD_PREFIX "and", Kw::And)
    (ZMBT_KEYWORD_PREFIX "∧", Kw::And)
    (ZMBT_KEYWORD_PREFIX "or", Kw::Or)
    (ZMBT_KEYWORD_PREFIX "∨", Kw::Or)
    (ZMBT_KEYWORD_PREFIX "xor", Kw::Xor)
    (ZMBT_KEYWORD_PREFIX "⊕", Kw::Xor)
    (ZMBT_KEYWORD_PREFIX "eq", Kw::Eq)
    (ZMBT_KEYWORD_PREFIX "=", Kw::Eq)
    (ZMBT_KEYWORD_PREFIX "ne", Kw::Ne)
    (ZMBT_KEYWORD_PREFIX "≠", Kw::Ne)
    (ZMBT_KEYWORD_PREFIX "lt", Kw::Lt)
    (ZMBT_KEYWORD_PREFIX "<", Kw::Lt)
    (ZMBT_KEYWORD_PREFIX "le", Kw::Le)
    (ZMBT_KEYWORD_PREFIX "≤", Kw::Le)
    (ZMBT_KEYWORD_PREFIX "gt", Kw::Gt)
    (ZMBT_KEYWORD_PREFIX ">", Kw::Gt)
    (ZMBT_KEYWORD_PREFIX "ge", Kw::Ge)
    (ZMBT_KEYWORD_PREFIX "≥", Kw::Ge)
    (ZMBT_KEYWORD_PREFIX "ni", Kw::Ni)
    (ZMBT_KEYWORD_PREFIX "∋", Kw::Ni)
    (ZMBT_KEYWORD_PREFIX "not-ni", Kw::NotNi)
    (ZMBT_KEYWORD_PREFIX "∌", Kw::NotNi)
    (ZMBT_KEYWORD_PREFIX "set-eq", Kw::SetEq)
    (ZMBT_KEYWORD_PREFIX "subset", Kw::Subset)
    (ZMBT_KEYWORD_PREFIX "⊆", Kw::Subset)
    (ZMBT_KEYWORD_PREFIX "superset", Kw::Superset)
    (ZMBT_KEYWORD_PREFIX "⊇", Kw::Superset)
    (ZMBT_KEYWORD_PREFIX "p-subset", Kw::ProperSubset)
    (ZMBT_KEYWORD_PREFIX "⊂", Kw::ProperSubset)
    (ZMBT_KEYWORD_PREFIX "p-superset", Kw::ProperSuperset)
    (ZMBT_KEYWORD_PREFIX "⊃", Kw::ProperSuperset)
    (ZMBT_KEYWORD_PREFIX "in", Kw::In)
    (ZMBT_KEYWORD_PREFIX "∈", Kw::In)
    (ZMBT_KEYWORD_PREFIX "not-in", Kw::NotIn)
    (ZMBT_KEYWORD_PREFIX "∉", Kw::NotIn)
    (ZMBT_KEYWORD_PREFIX "neg", Kw::Neg)
    (ZMBT_KEYWORD_PREFIX "abs", Kw::Abs)
    (ZMBT_KEYWORD_PREFIX "sign", Kw::Sign)
    (ZMBT_KEYWORD_PREFIX "ceil", Kw::Ceil)
    (ZMBT_KEYWORD_PREFIX "floor", Kw::Floor)
    (ZMBT_KEYWORD_PREFIX "round", Kw::Round)
    (ZMBT_KEYWORD_PREFIX "add", Kw::Add)
    (ZMBT_KEYWORD_PREFIX "+", Kw::Add)
    (ZMBT_KEYWORD_PREFIX "sub", Kw::Sub)
    (ZMBT_KEYWORD_PREFIX "-", Kw::Sub)
    (ZMBT_KEYWORD_PREFIX "mul", Kw::Mul)
    (ZMBT_KEYWORD_PREFIX "*", Kw::Mul)
    (ZMBT_KEYWORD_PREFIX "div", Kw::Div)
    (ZMBT_KEYWORD_PREFIX "/", Kw::Div)
    (ZMBT_KEYWORD_PREFIX "pow", Kw::Pow)
    (ZMBT_KEYWORD_PREFIX "**", Kw::Pow)
    (ZMBT_KEYWORD_PREFIX "log", Kw::Log)
    (ZMBT_KEYWORD_PREFIX "mod", Kw::Mod)
    (ZMBT_KEYWORD_PREFIX "%", Kw::Mod)
    (ZMBT_KEYWORD_PREFIX "quot", Kw::Quot)
    (ZMBT_KEYWORD_PREFIX "//", Kw::Quot)
    (ZMBT_KEYWORD_PREFIX "sqrt", Kw::Sqrt)
    (ZMBT_KEYWORD_PREFIX "sin", Kw::Sin)
    (ZMBT_KEYWORD_PREFIX "cos", Kw::Cos)
    (ZMBT_KEYWORD_PREFIX "tan", Kw::Tan)
    (ZMBT_KEYWORD_PREFIX "asin", Kw::Asin)
    (ZMBT_KEYWORD_PREFIX "acos", Kw::Acos)
    (ZMBT_KEYWORD_PREFIX "atan", Kw::Atan)
    (ZMBT_KEYWORD_PREFIX "sinh", Kw::Sinh)
    (ZMBT_KEYWORD_PREFIX "cosh", Kw::Cosh)
    (ZMBT_KEYWORD_PREFIX "tanh", Kw::Tanh)
    (ZMBT_KEYWORD_PREFIX "asinh", Kw::Asinh)
    (ZMBT_KEYWORD_PREFIX "acosh", Kw::Acosh)
    (ZMBT_KEYWORD_PREFIX "atanh", Kw::Atanh)
    (ZMBT_KEYWORD_PREFIX "exp", Kw::Exp)
    (ZMBT_KEYWORD_PREFIX "erf", Kw::Erf)
    (ZMBT_KEYWORD_PREFIX "erfc", Kw::Erfc)
    (ZMBT_KEYWORD_PREFIX "gamma", Kw::Gamma)
    (ZMBT_KEYWORD_PREFIX "b-not", Kw::BitNot)
    (ZMBT_KEYWORD_PREFIX "~", Kw::BitNot)
    (ZMBT_KEYWORD_PREFIX "b-and", Kw::BitAnd)
    (ZMBT_KEYWORD_PREFIX "|", Kw::BitAnd)
    (ZMBT_KEYWORD_PREFIX "b-or", Kw::BitOr)
    (ZMBT_KEYWORD_PREFIX "^", Kw::BitOr)
    (ZMBT_KEYWORD_PREFIX "b-xor", Kw::BitXor)
    (ZMBT_KEYWORD_PREFIX "~", Kw::BitXor)
    (ZMBT_KEYWORD_PREFIX "b-lshift", Kw::BitLshift)
    (ZMBT_KEYWORD_PREFIX "<<", Kw::BitLshift)
    (ZMBT_KEYWORD_PREFIX "b-rshift", Kw::BitRshift)
    (ZMBT_KEYWORD_PREFIX ">>", Kw::BitRshift)
    (ZMBT_KEYWORD_PREFIX "map", Kw::Map)
    (ZMBT_KEYWORD_PREFIX "filter", Kw::Filter)
    (ZMBT_KEYWORD_PREFIX "compose", Kw::Compose)
    (ZMBT_KEYWORD_PREFIX "recur", Kw::Recur)
    (ZMBT_KEYWORD_PREFIX "apply", Kw::Apply)
    (ZMBT_KEYWORD_PREFIX "partial", Kw::Partial)
    (ZMBT_KEYWORD_PREFIX "reduce", Kw::Reduce)
    (ZMBT_KEYWORD_PREFIX "concat", Kw::Concat)
    (ZMBT_KEYWORD_PREFIX "union", Kw::Union)
    (ZMBT_KEYWORD_PREFIX "∪", Kw::Union)
    (ZMBT_KEYWORD_PREFIX "intersect", Kw::Intersect)
    (ZMBT_KEYWORD_PREFIX "∩", Kw::Intersect)
    (ZMBT_KEYWORD_PREFIX "set-diff", Kw::Diff)
    (ZMBT_KEYWORD_PREFIX "cartesian", Kw::Cartesian)
    (ZMBT_KEYWORD_PREFIX "transp", Kw::Transp)
    (ZMBT_KEYWORD_PREFIX "set", Kw::Set)
    (ZMBT_KEYWORD_PREFIX "list", Kw::List)
    (ZMBT_KEYWORD_PREFIX "slide", Kw::Slide)
    (ZMBT_KEYWORD_PREFIX "stride", Kw::Stride)
    (ZMBT_KEYWORD_PREFIX "slice", Kw::Slice)
    (ZMBT_KEYWORD_PREFIX "sort", Kw::Sort)
    (ZMBT_KEYWORD_PREFIX "repeat", Kw::Repeat)
    (ZMBT_KEYWORD_PREFIX "at", Kw::At)
    (ZMBT_KEYWORD_PREFIX "sum", Kw::Sum)
    (ZMBT_KEYWORD_PREFIX "Σ", Kw::Sum)
    (ZMBT_KEYWORD_PREFIX "prod", Kw::Prod)
    (ZMBT_KEYWORD_PREFIX "Π", Kw::Prod)
    (ZMBT_KEYWORD_PREFIX "card", Kw::Card)
    (ZMBT_KEYWORD_PREFIX "size", Kw::Size)
    (ZMBT_KEYWORD_PREFIX "count", Kw::Count)
    (ZMBT_KEYWORD_PREFIX "min", Kw::Min)
    (ZMBT_KEYWORD_PREFIX "max", Kw::Max)
    (ZMBT_KEYWORD_PREFIX "argmin", Kw::Argmin)
    (ZMBT_KEYWORD_PREFIX "argmax", Kw::Argmax)
    (ZMBT_KEYWORD_PREFIX "any", Kw::Any)
    (ZMBT_KEYWORD_PREFIX "all", Kw::All)
    (ZMBT_KEYWORD_PREFIX "saturate", Kw::Saturate)
    (ZMBT_KEYWORD_PREFIX "re", Kw::Re)
    (ZMBT_KEYWORD_PREFIX "approx", Kw::Approx)
    ;
}


KeywordGrammar::KeywordGrammar()
    : KeywordGrammar::base_type(start)
{
    using boost::spirit::qi::eps;
    using boost::spirit::qi::_val;
    using boost::spirit::qi::_1;

    start = eps [_val = Keyword::Undefined] >>
        (
            +keyword_symbol [_val = _1]
        )
    ;
}

} // namespace zmbt

