/**
 * \file
 * \copyright (c) Copyright 2024-2025 Zenseact AB
 * \license SPDX-License-Identifier: Apache-2.0
 *
 * \details Autogenerated file - do not change!
 *
 * app: codegen.expr
 * template: codegen/expr/templates/zmbt-framework/backends/cxx/src/model/keyword_is_boolean.cpp
 *
 * How to update:
 * 1. Update the template
 * 2. Run `python -m codegen` in the project root
 * 3. Commit changes
 */

#include "zmbt/model/keyword.hpp"


namespace zmbt {
namespace dsl {
namespace detail {

bool isBoolean(Keyword const& k)
{
    switch (k)
    {
    case Keyword::True:
    case Keyword::False:
    case Keyword::Eq:
    case Keyword::Ne:
    case Keyword::Lt:
    case Keyword::Le:
    case Keyword::Gt:
    case Keyword::Ge:
    case Keyword::Approx:
    case Keyword::SetEq:
    case Keyword::Subset:
    case Keyword::Superset:
    case Keyword::ProperSubset:
    case Keyword::ProperSuperset:
    case Keyword::In:
    case Keyword::NotIn:
    case Keyword::Ni:
    case Keyword::NotNi:
    case Keyword::Bool:
    case Keyword::Not:
    case Keyword::Re:
    case Keyword::Each:
    case Keyword::Any:
    case Keyword::All:
    case Keyword::Saturate:
        return true;
    default:
        return false;
    }
}

} // namespace detail
} // namespace dsl
} // namespace zmbt
