/**
 * \file
 * \copyright (c) Copyright 2024-2025 Zenseact AB
 * \license SPDX-License-Identifier: Apache-2.0
 *
 * \details Autogenerated file - do not change!
 *
 * app: codegen.expr
 * template: codegen/expr/templates/keyword_is_binary.cpp
 *
 * How to update:
 * 1. Update the template
 * 2. Run `python -m codegen` in the project root
 * 3. Commit changes
 */

#include "zmbt/model/keyword.hpp"


namespace zmbt {
namespace expr {
namespace detail {

bool isBinary(Keyword const& k)
{
    switch (k)
    {
    case Keyword::Add:
    case Keyword::And:
    case Keyword::Approx:
    case Keyword::At:
    case Keyword::BitAnd:
    case Keyword::BitLshift:
    case Keyword::BitLshiftFrom:
    case Keyword::BitOr:
    case Keyword::BitRshift:
    case Keyword::BitRshiftFrom:
    case Keyword::BitXor:
    case Keyword::Concat:
    case Keyword::Default:
    case Keyword::Div:
    case Keyword::DivFrom:
    case Keyword::Eq:
    case Keyword::Format:
    case Keyword::Ge:
    case Keyword::Gt:
    case Keyword::In:
    case Keyword::Intersect:
    case Keyword::Le:
    case Keyword::Log:
    case Keyword::LogFrom:
    case Keyword::Lt:
    case Keyword::Mod:
    case Keyword::ModFrom:
    case Keyword::Mul:
    case Keyword::Ne:
    case Keyword::Ni:
    case Keyword::NotIn:
    case Keyword::NotNi:
    case Keyword::Or:
    case Keyword::ProperSubset:
    case Keyword::ProperSuperset:
    case Keyword::Pow:
    case Keyword::PowFrom:
    case Keyword::Quot:
    case Keyword::QuotFrom:
    case Keyword::Re:
    case Keyword::Repeat:
    case Keyword::Diff:
    case Keyword::DiffFrom:
    case Keyword::SetEq:
    case Keyword::Slide:
    case Keyword::Stride:
    case Keyword::Sub:
    case Keyword::SubFrom:
    case Keyword::Subset:
    case Keyword::Superset:
    case Keyword::Try:
    case Keyword::TryCatch:
    case Keyword::Union:
        return true;
    default:
        return false;
    }
}

} // namespace detail
} // namespace expr
} // namespace zmbt
