@require(data)
/**
 * \file
 * \copyright (c) Copyright 2024-2025 Zenseact AB
 * \license SPDX-License-Identifier: Apache-2.0
 *
 * \details Autogenerated file - do not change!
 *
 * app: @appname
 * generated: @timestamp
 * template: @template
 *
 * How to update:
 * 1. Update the template
 * 2. Run `python -m codegen` in the project root
 * 3. Commit changes
 */

#ifndef ZMBT_MODEL_EXPRESSION_API_HPP_
#define ZMBT_MODEL_EXPRESSION_API_HPP_

#include "expression_api_signatures.hpp"

namespace zmbt {
namespace expr {

@for keyword in data.Keywords:

/// \brief @keyword.DocBrief
    @if details := keyword.DocDetails:
/// \details
        @for line in details.split('\n'):
/// @line
        @end
    @end
static signature::@keyword.Class const @keyword.Enum;
@for alias in keyword.Aliases:
/// \brief Alias for @keyword.Enum
static signature::@keyword.Class const @alias.capitalize();
@end
@end

} // namespace expr
} // namespace zmbt

#endif // ZMBT_MAPPING_EXPRESSION_HPP_
