@require(data)
/**
 * \file
 * \copyright (c) Copyright 2024-2025 Zenseact AB
 * \license SPDX-License-Identifier: Apache-2.0
 *
 * \details Autogenerated file - do not change!
 *
 * app: @appname
 * template: @template
 *
 * How to update:
 * 1. Update the template
 * 2. Run `python -m codegen` in the project root
 * 3. Commit changes
 */


#include "zmbt/model/expression_api.hpp"

namespace zmbt {
namespace api {

@for keyword in data.ApiKeywords:
expr::@keyword.Class const @keyword.Enum = {};
@for alias in keyword.Aliases:
expr::@keyword.Class const @alias.capitalize() = @keyword.Enum;
@end
@end

} // namespace api
} // namespace zmbt
