@require(data)
/**
 * \file
 * \copyright (c) Copyright 2024-2025 Zenseact AB
 * \license SPDX-License-Identifier: Apache-2.0
 *
 * \details Autogenerated file - do not change!
 *
 * app: @appname
 * template: @template
 *
 * How to update:
 * 1. Update the template
 * 2. Run `python -m codegen` in the project root
 * 3. Commit changes
 */

#include "zmbt/model/keyword_classifier.hpp"


namespace zmbt {
namespace expr {

KeywordClassifier getKeywordClassifier(Keyword const& k)
{
    switch (k)
    {
@for keyword in data.Keywords:
    case Keyword::@keyword.Enum: return {Category::@keyword.Category, Signature::@keyword.Signature};
@end
    default:
        return {Category::Undefined, Signature::Undefined};
    }
}

} // namespace expr
} // namespace zmbt
