@require(data)
/**
 * \file
 * \copyright (c) Copyright 2024-2025 Zenseact AB
 * \license SPDX-License-Identifier: Apache-2.0
 *
 * \details Autogenerated file - do not change!
 *
 * app: @appname
 * template: @template
 *
 * How to update:
 * 1. Update the template
 * 2. Run `python -m codegen` in the project root
 * 3. Commit changes
 */

#include <boost/spirit/include/qi.hpp>

#include "zmbt/model/keyword.hpp"
#include "zmbt/model/keyword_grammar.hpp"

#ifndef ZMBT_KEYWORD_PREFIX
    #define ZMBT_KEYWORD_PREFIX ":"
#endif

namespace qi = boost::spirit::qi;

namespace zmbt {
namespace expr {


KeywordSymbol::KeywordSymbol()
{
    add
@for keyword in data.Keywords:
    (ZMBT_KEYWORD_PREFIX "@keyword.Name", Keyword::@keyword.Enum)
    @if short := keyword.Short:
    (ZMBT_KEYWORD_PREFIX "@short", Keyword::@keyword.Enum)
    @end
    @for alias in keyword.Aliases:
    (ZMBT_KEYWORD_PREFIX "@alias", Keyword::@keyword.Enum)
    @end
@end
    ;
}


KeywordGrammar::KeywordGrammar()
    : KeywordGrammar::base_type(start)
{
    using boost::spirit::qi::eps;
    using boost::spirit::qi::_val;
    using boost::spirit::qi::_1;

    start = eps [_val = Keyword::Undefined] >>
        (
            +keyword_symbol [_val = _1]
        )
    ;
}

} // namespace expr
} // namespace zmbt
