@require(data)
/**
 * \file
 * \copyright (c) Copyright 2024-2025 Zenseact AB
 * \license SPDX-License-Identifier: Apache-2.0
 *
 * \details Autogenerated file - do not change!
 *
 * app: @appname
 * template: @template
 *
 * How to update:
 * 1. Update the template
 * 2. Run `python -m codegen` in the project root
 * 3. Commit changes
 */

#include "zmbt/model/keyword_classifier.hpp"


namespace zmbt {
namespace expr {
namespace detail {


Classifier getKeywordClassifier(Keyword const& k)
{
    switch (k)
    {
@for keyword in data.Internals:
    case Keyword::@keyword.Enum:
@end
        return Classifier::Internal;
@for keyword in data.Constants:
    case Keyword::@keyword.Enum:
@end
        return Classifier::Const;
@for keyword in data.UnaryOperators:
    case Keyword::@keyword.Enum:
@end
        return Classifier::UnaryOp;
@for keyword in data.CodegenFns:
    case Keyword::@keyword.Enum:
@end
        return Classifier::UnaryMathFn;
@for keyword in data.BinaryOperators:
    case Keyword::@keyword.Enum:
@end
        return Classifier::BinaryOp;
    default:
        return Classifier::Special;
    }

}

} // namespace detail
} // namespace expr
} // namespace zmbt
