name: Test and Scan Python

on:
  push:
    tags: [ "*" ]
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  codeql-scan-python:
    name: CodeQL scan Python
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read

    strategy:
      fail-fast: false
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: python
        build-mode: none

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:python"
